# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-03-16 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='AadhaarNo',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='Age',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
