# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-03-17 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0002_auto_20210316_1434'),
    ]

    operations = [
        migrations.AddField(
            model_name='teamregister',
            name='Team_slug',
            field=models.SlugField(default='',null=True),
        ),
    ]
