# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2021-03-17 03:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teams', '0010_auto_20210317_0246'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Captain',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='Wicket_keeper',
            field=models.BooleanField(default=False),
        ),
    ]
